
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shash
 */
public class REGISTERfORM extends javax.swing.JFrame {
Connection conn=null;
    PreparedStatement pst;
    ResultSet rs;
    
    
    /**
     * Creates new form REGISTERfORM
     */
    public REGISTERfORM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RUser = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        RPass = new javax.swing.JLabel();
        RPhone = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        RGen = new javax.swing.JLabel();
        acctype = new javax.swing.JComboBox<>();
        RACType = new javax.swing.JLabel();
        RAccountNum = new javax.swing.JLabel();
        accno = new javax.swing.JTextField();
        RDOB = new javax.swing.JLabel();
        dob = new javax.swing.JTextField();
        RMICR = new javax.swing.JLabel();
        micr = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        rpass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        ACGenerateButton = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 877, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 877, -1));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Registration Form");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 39, -1, -1));

        RUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MiniProjIcons/user-fill.png"))); // NOI18N
        getContentPane().add(RUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, 30));

        name.setToolTipText("");
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nameMouseEntered(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 86, 217, 33));

        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emailMouseEntered(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 138, 217, 30));

        RPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MiniProjIcons/lock-fill.png"))); // NOI18N
        getContentPane().add(RPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, 32));

        RPhone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MiniProjIcons/phone-fill.png"))); // NOI18N
        getContentPane().add(RPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 223, -1, 31));

        phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                phoneMouseEntered(evt);
            }
        });
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneKeyTyped(evt);
            }
        });
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 223, 217, 31));

        Submit.setBackground(new java.awt.Color(255, 255, 255));
        Submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Submit.setText("SUBMIT");
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubmitMouseEntered(evt);
            }
        });
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, 398, 110, 40));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 877, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 465, 877, -1));

        RGen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        RGen.setText("Gender");
        getContentPane().add(RGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 60, 25));

        acctype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Savings", "Current" }));
        acctype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                acctypeMouseEntered(evt);
            }
        });
        acctype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acctypeActionPerformed(evt);
            }
        });
        getContentPane().add(acctype, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 217, 31));

        RACType.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        RACType.setText("Account Type");
        getContentPane().add(RACType, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 22));

        RAccountNum.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        RAccountNum.setText("Account Number");
        getContentPane().add(RAccountNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 103, 30));

        accno.setEditable(false);
        accno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accnoMouseEntered(evt);
            }
        });
        accno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accnoActionPerformed(evt);
            }
        });
        getContentPane().add(accno, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 155, 30));

        RDOB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        RDOB.setText("Date of Birth");
        getContentPane().add(RDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 85, 32));

        dob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dobMouseEntered(evt);
            }
        });
        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 155, 32));

        RMICR.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        RMICR.setText("IFSC Code");
        getContentPane().add(RMICR, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 77, 26));

        micr.setText("ACE100");
        micr.setEnabled(false);
        micr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                micrMouseEntered(evt);
            }
        });
        micr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                micrActionPerformed(evt);
            }
        });
        getContentPane().add(micr, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 155, 31));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));
        gender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                genderMouseEntered(evt);
            }
        });
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 150, 30));

        rpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rpassMouseEntered(evt);
            }
        });
        rpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpassActionPerformed(evt);
            }
        });
        getContentPane().add(rpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 179, 217, 31));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MiniProjIcons/mail-fill.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MiniProjIcons/rupee (1).png"))); // NOI18N
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 40, 30));

        amount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                amountMouseEntered(evt);
            }
        });
        amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amountKeyTyped(evt);
            }
        });
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 160, 30));

        ACGenerateButton.setText("Generate");
        ACGenerateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ACGenerateButtonMouseEntered(evt);
            }
        });
        ACGenerateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACGenerateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ACGenerateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*public String RandomAcc(){
        Random ra=new Random();
        String accno=""+ra.nextInt(10000+1);
        return accno;
        //accno.setText(""+ra.nextInt(10000+1));
    }
    public void Bal(){
        String sql="insert into balances values(?,?,?,?)";
        try{
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, name.getText());
            pst.setString(2, accno.getText());
            pst.setString(3, "ACE100");
            pst.setString(4, "10000");
            pst.executeQuery(sql);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }*/
    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
if(verifyPass()){
 if(verifyEmail()){   

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/bank","root","");
            String q="insert into registerform values(?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pt= (PreparedStatement) con.prepareStatement(q);
            pt.setString(1,name.getText());
            pt.setString(2,email.getText());
            pt.setString(3,new String(rpass.getPassword()));
            pt.setString(4,phone.getText());
            String at ="";
            at = acctype.getSelectedItem().toString();
             pt.setString(5, at);
            String gen ="";
             gen = gender.getSelectedItem().toString();
             pt.setString(6, gen);
            pt.setString(7, accno.getText());
            pt.setString(8,dob.getText());
            pt.setString(9,"ACE100");
            pt.setString(10,amount.getText());
            pt.executeUpdate();
            String w = "insert into login values(?,?)";
             PreparedStatement ps = con.prepareStatement(w);
             ps.setString(1, name.getText());
             ps.setString(2, new String(rpass.getPassword()));
             ps.executeUpdate();
             
             /*String a = "insert into accounts value(?,?,?,?,?,?,?,?,?)";
             PreparedStatement cs = con.prepareStatement(a);
             cs.setString(1, name.getText());
             cs.setString(2, email.getText());
             cs.setString(3, phone.getText());
             cs.setString(4, acctype.getSelectedItem().toString());
             cs.setString(5, gender.getSelectedItem().toString());
             cs.setString(6, accno.getText());
             cs.setString(7, dob.getText());
             cs.setString(8, amount.getText());
             cs.executeUpdate();*/
             String a = "insert into balances values (?,?,?,?)";
             PreparedStatement cs = con.prepareStatement(a);
             cs.setString(1, name.getText());
             cs.setString(2, accno.getText());
             cs.setString(3, "ACE100");
             //cs.setString(4, Integer.parseInt(amount.getText());
             cs.setString(4, amount.getText());
             cs.executeUpdate();
             
             
            JOptionPane.showMessageDialog(null,"REGISTERED SUCCESSFULLY");
            con.close();
            dispose();
         Login l=new Login();
         l.setVisible(true);
         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
 }
}
//TODO add your handling code here
    }//GEN-LAST:event_SubmitActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void acctypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acctypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acctypeActionPerformed

    private void accnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accnoActionPerformed

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed

    private void micrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_micrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_micrActionPerformed

    private void rpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rpassActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void nameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseEntered
        // TODO add your handling code here:
        name.setToolTipText("Enter your Name");
    }//GEN-LAST:event_nameMouseEntered

    private void emailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseEntered
        // TODO add your handling code here:
        email.setToolTipText("Enter your EMail");
    }//GEN-LAST:event_emailMouseEntered

    private void rpassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rpassMouseEntered
        // TODO add your handling code here:
        rpass.setToolTipText("Enter your Password");
    }//GEN-LAST:event_rpassMouseEntered

    private void phoneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneMouseEntered
        // TODO add your handling code here:
        phone.setToolTipText("Enter your PhoneNumber");
    }//GEN-LAST:event_phoneMouseEntered

    private void acctypeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acctypeMouseEntered
        // TODO add your handling code here:
        acctype.setToolTipText("Choose the Account Type");
    }//GEN-LAST:event_acctypeMouseEntered

    private void genderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genderMouseEntered
        // TODO add your handling code here:
        gender.setToolTipText("Choose the Gender");
    }//GEN-LAST:event_genderMouseEntered

    private void accnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accnoMouseEntered
        // TODO add your handling code here:
        accno.setToolTipText("Account Number");
    }//GEN-LAST:event_accnoMouseEntered

    private void dobMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dobMouseEntered
        // TODO add your handling code here:
        dob.setToolTipText("DD-MM-YYYY");
    }//GEN-LAST:event_dobMouseEntered

    private void micrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_micrMouseEntered
        // TODO add your handling code here:
        micr.setToolTipText("IFSC Code");
    }//GEN-LAST:event_micrMouseEntered

    private void SubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseEntered
        // TODO add your handling code here:
        Submit.setToolTipText("Submit");
    }//GEN-LAST:event_SubmitMouseEntered

    private void ACGenerateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACGenerateButtonActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3307/bank","root","");
            Statement st= con1.createStatement();
            ResultSet rs= st.executeQuery("select Max(AccountNumber) from registerform");
            if(rs.first()){
                int id = rs.getInt(1);
                id = id+10;
                String str = String.valueOf(id);
                accno.setText(str);
            }
            else{
                accno.setText("1000");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_ACGenerateButtonActionPerformed

    private void phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)){evt.consume();}
    }//GEN-LAST:event_phoneKeyTyped

    private void ACGenerateButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACGenerateButtonMouseEntered
        // TODO add your handling code here:
        ACGenerateButton.setToolTipText("Generate");
    }//GEN-LAST:event_ACGenerateButtonMouseEntered

    private void amountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amountMouseEntered
        // TODO add your handling code here:
        amount.setToolTipText("Enter the amount");
    }//GEN-LAST:event_amountMouseEntered

    private void amountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)){evt.consume();}
    }//GEN-LAST:event_amountKeyTyped
public boolean verifyPass() {
        String pass= rpass.getText();
        int digCount = 0;
        int capsCount = 0;
        int specCount = 0;
        
        for (int i = 0 ; i < pass.length() ; i++) {
            if (pass.charAt(i) >= 48 && pass.charAt(i) <= 57)
                digCount ++;//|| (word.charAt(i) >= 97 && word.charAt(i) <= 122) || (word.charAt(i) >= 65 && word.charAt(i) <= 90));
            else if (pass.charAt(i) >= 65 && pass.charAt(i) <= 90)
                capsCount ++;
            
            if ((pass.charAt(i) >= 48 && pass.charAt(i) <= 57) || (pass.charAt(i) >= 97 && pass.charAt(i) <= 122) || (pass.charAt(i) >= 65 && pass.charAt(i) <= 90));
            else if (pass.charAt(i) == 32)
                specCount --;
            else
                specCount ++;
        }

        if (specCount >= 2 && digCount >= 2 && capsCount >= 1)
        {
            return true;}
            else{
            JOptionPane.showMessageDialog(null,"Invalid password", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
            } 
}
  public boolean verifyEmail(){
        if (!(Pattern.matches("^[A-Za-z0-9+_.-]+@(.+)$", email.getText())))
    {
    JOptionPane.showMessageDialog(null,"Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
    return false;
    }
else{
    return true;
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REGISTERfORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REGISTERfORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REGISTERfORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REGISTERfORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REGISTERfORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACGenerateButton;
    private javax.swing.JLabel RACType;
    private javax.swing.JLabel RAccountNum;
    private javax.swing.JLabel RDOB;
    private javax.swing.JLabel RGen;
    private javax.swing.JLabel RMICR;
    private javax.swing.JLabel RPass;
    private javax.swing.JLabel RPhone;
    private javax.swing.JLabel RUser;
    private javax.swing.JButton Submit;
    private javax.swing.JTextField accno;
    private javax.swing.JComboBox<String> acctype;
    private javax.swing.JTextField amount;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField micr;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JPasswordField rpass;
    // End of variables declaration//GEN-END:variables
}
